########################################
# Docker                               #
#                                      #
# A NodeJS container that enables the  #
# application to run                   #
########################################

FROM node:8-alpine

LABEL maintainer "<%- author %>"

# Set the work directory and add the project files to it
WORKDIR /opt/app
ADD . /opt/app

# Environment variables
ENV <%- envvarPrefix %>LOGGING_STREAMS_STDOUT_ACTIVE=true
ENV <%- envvarPrefix %>LOGGING_STREAMS_STDOUT_LEVEL=info

ENV <%- envvarPrefix %>SERVER_PORT=9999

# Set the user as host's current user
RUN chown -Rf node:node /opt/app
USER node

# Install the dependencies
RUN npm install

# Expose the ports
EXPOSE 9999 5858

# Run run run
CMD npm start
